services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Film
    command: 
      - "postgres"
      - "-c"
      - "listen_addresses=*"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/backup:/backup
      - ./database/restore.sh:/docker-entrypoint-initdb.d/restore.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - app-network
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
